"""Gradient checks for the hand-written MLP backward pass.

Same method as the neural-bigram checks: each analytic gradient (here from
``neural_mlp.backward``) is compared against a numerical one, obtained by
perturbing each entry by +-epsilon and measuring the change in loss via
central differences. Agreement within tolerance is evidence the derivation
is correct.

What is under test here is the assembled orchestrator. ``backward`` returns
the five parameter gradients ``(dC, dW1, db1, dW2, db2)``; one test per
parameter perturbs that parameter through the full forward pass and checks
its gradient. Because each check runs the whole pipeline, the per-link math
(generic, and living in ``neural``) is exercised transitively: a wrong link
would surface as a wrong parameter gradient. The five tests together also
guard the wiring -- the order of the links and of the returned tuple.

float64 throughout, since finite differences are too noisy in float32.

This code has been generated by Claude.ai.
"""
import pytest
import numpy as np

from makemore import data, neural, neural_mlp


# Constants
SEED = 2147483647
EPSILON = 1e-5

BLOCK_SIZE = 3
N_EMB = 2
HIDDEN_LAYER_OUTPUTS = 8     # kept small: the test checks wiring, not capacity


def _forward_loss(params: dict, X: np.ndarray, Y: np.ndarray) -> float:
    """Full MLP forward, from the current parameters down to the mean NLL loss.

    Reads the parameters from ``params`` every call, so an in-place perturbation
    of any parameter is reflected here -- this is what the finite differences ride on.
    """
    concat = neural.concatenate_embs(neural.embed(X, params["C"]))
    activations = np.tanh(neural.linear_forward(concat, params["W1"]) + params["b1"])
    logits = neural.linear_forward(activations, params["W2"]) + params["b2"]
    return neural.mean_nll(neural.softmax(logits), Y)


def _numeric_grad(param: np.ndarray, params: dict, X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    """Central-difference gradient of the loss w.r.t. one parameter array.

    ``param`` must be the very array stored in ``params`` (same object), so that
    perturbing it in place changes what ``_forward_loss`` recomputes. Each entry
    is restored before moving on, leaving the parameters as they were.
    """
    grad = np.zeros_like(param)
    it = np.nditer(param, flags=["multi_index"])
    for _ in it:
        idx = it.multi_index
        original = param[idx]

        param[idx] = original + EPSILON
        loss_plus = _forward_loss(params, X, Y)

        param[idx] = original - EPSILON
        loss_minus = _forward_loss(params, X, Y)

        param[idx] = original

        grad[idx] = (loss_plus - loss_minus) / (2 * EPSILON)
    return grad


@pytest.fixture
def mlp_setup():
    """One full forward pass on a tiny fixed dataset, plus the analytic gradients.

    Returns (params, grads, X, Y), where ``params`` is the dict of the five
    parameters (cast to float64 so finite differences are not swamped by
    float32 noise) and ``grads`` is the tuple returned by ``neural_mlp.backward``,
    computed at the unperturbed parameters. pytest re-runs this per test, so
    each check starts from a clean copy.
    """
    # --- Arrange: prepare the situation ---

    # 1. Prepare the dataset. Small, but with indices that repeat in X.
    raw_dataset = ["emma", "olivia", "ava"]
    stoi, itos = data.build_vocab(raw_dataset)
    X, Y = data.build_dataset(raw_dataset, stoi, BLOCK_SIZE)
    alphabet_len = len(stoi)

    # 2. Initialize the parameters (float64 from the start).
    rng = np.random.default_rng(SEED)
    C  = neural.build_layer(alphabet_len, N_EMB, rng).astype(np.float64)
    W1 = neural.build_layer(BLOCK_SIZE * N_EMB, HIDDEN_LAYER_OUTPUTS, rng).astype(np.float64)
    b1 = neural.create_biases(HIDDEN_LAYER_OUTPUTS, rng).astype(np.float64)
    W2 = neural.build_layer(HIDDEN_LAYER_OUTPUTS, alphabet_len, rng).astype(np.float64)
    b2 = neural.create_biases(alphabet_len, rng).astype(np.float64)
    params = {"C": C, "W1": W1, "b1": b1, "W2": W2, "b2": b2}

    # 3. Forward pass: the quantities the backward consumes.
    concat = neural.concatenate_embs(neural.embed(X, C))
    activations = np.tanh(neural.linear_forward(concat, W1) + b1)
    logits = neural.linear_forward(activations, W2) + b2
    probs = neural.softmax(logits)

    # 4. Analytic gradients from the orchestrator under test.
    grads = neural_mlp.backward(
        alphabet_len, BLOCK_SIZE, N_EMB, X, Y, concat, W1, W2, activations, probs
    )

    return params, grads, X, Y


# backward returns (dC, dW1, db1, dW2, db2); these indices name that order.
_dC, _dW1, _db1, _dW2, _db2 = range(5)


def _check(name: str, analytic: np.ndarray, params: dict, key: str, X, Y):
    """Run the numeric gradient for one parameter and assert it matches."""
    numeric = _numeric_grad(params[key], params, X, Y)

    # Use the "-s" option to print
    print(f"[{name}] shape={analytic.shape} max|Δ|={np.abs(analytic - numeric).max():.2e}")

    assert np.allclose(analytic, numeric, atol=1e-6)


def test_dC_matches_numerical_gradient(mlp_setup):
    """Check dL/dC: the embedding-table gradient (the scatter-add link)."""
    params, grads, X, Y = mlp_setup
    _check("dC", grads[_dC], params, "C", X, Y)


def test_dW1_matches_numerical_gradient(mlp_setup):
    """Check dL/dW1: the hidden layer's weights."""
    params, grads, X, Y = mlp_setup
    _check("dW1", grads[_dW1], params, "W1", X, Y)


def test_db1_matches_numerical_gradient(mlp_setup):
    """Check dL/db1: the hidden layer's bias (summed over the batch)."""
    params, grads, X, Y = mlp_setup
    _check("db1", grads[_db1], params, "b1", X, Y)


def test_dW2_matches_numerical_gradient(mlp_setup):
    """Check dL/dW2: the output layer's weights."""
    params, grads, X, Y = mlp_setup
    _check("dW2", grads[_dW2], params, "W2", X, Y)


def test_db2_matches_numerical_gradient(mlp_setup):
    """Check dL/db2: the output layer's bias (summed over the batch)."""
    params, grads, X, Y = mlp_setup
    _check("db2", grads[_db2], params, "b2", X, Y)
